### ISSUE TITLE
Chat auto login

### ISSUE THREAD

**Issue by karambir** [fpytloun/django-xmpp#1]
Hi,

Thanks for this. Can we setup this app and have our converse js chat window auto login to whichever user is logged in currently on Django site? I tested https://github.com/TracyWebTech/django-conversejs and this does not do auto-login.

If we can't, is this something that you may want to add in future? I can help with this.

**Comment by fpytloun** [comment]
Hello,

thank you for your interest in django-xmpp!

Yes, SSO functionality is possible in case you will use ejabberd_auth management command as ejabberd external authentication script. This is described in readme here: https://github.com/fpytloun/django-xmpp#ejabberd-django-authentication

I use the same approach in my project https://www.routebacker.com (you need to be logged in first). ConverseJS is authenticated by generated webapp password but user still can use his real password to log in from eg. desktop client.

django-conversejs uses different approach - it saves user real XMPP password in database (in plain text as far as I know) and tries to use it to simulate SSO behavior.

**Comment by jcbrand** [comment]
This approach is definitely better than storing plaintext passwords and trying to auth with a builtin BOSH client.

There is a similar module for Prosody: [mod_auth_http_async](https://code.google.com/p/prosody-modules/source/browse/mod_auth_http_async/mod_auth_http_async.lua), which lets Prosody defer auth to an external server via HTTP.

That should probably work with this module without much modification.

**Comment by karambir** [comment]
Thanks @fpytloun. We tried and it is working superb,

**Comment by fpytloun** [comment]
Great, good to hear that! :-)
