### ISSUE TITLE
Logging out does not terminate sessions

### ISSUE THREAD

**Issue by alexandervlpl** [fpytloun/django-xmpp#11]
When one Django user logs out and another logs in (same browser), Converse continues to authenticate using the previous user's account. Confusing for users, and a serious security issue. :wink:  We need to terminate/reset the session if the user changes.

**Comment by fpytloun** [comment]
This seems to be valid bug, pull request will be appreciated :-)

**Comment by fpytloun** [comment]
Fixed by https://github.com/fpytloun/django-xmpp/pull/12
