### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by yashwanthbabu** [fpytloun/django-xmpp#2]
Hi,

While integration with this my Django project, Everything related to conversjs loads but the Authentication is failed. You can see the screenshot below. All the instructions given in README are followed even though raising the error

![screen shot 2015-06-25 at 3 02 37 pm](https://cloud.githubusercontent.com/assets/7446464/8351488/411f4904-1b4b-11e5-95db-0f659ef31496.png)

**Comment by fpytloun** [comment]
Hello,

if you have debug enabled, you should be able to see ConverseJS logs in browser's console.
You can also check `conversejs.init` and it's parameters - especially generated webapp login/password which it tries to use. Try to log in with this user/password with different Jabber client to see if ejabberd auth against django works fine.

Unfortunately I can't provide more help without some informations.

**Comment by yashwanthbabu** [comment]
@fpytloun I have check the parametes and it gives me Jid and Password. Using those credentials I can't able to login in any of the Jabber Client. Is there any problem with this?

**Comment by fpytloun** [comment]
So the problem is probably on ejabberd side.
Check ejabberd logs for some errors and verify it's using external auth script correctly.

**Comment by yashwanthbabu** [comment]
@fpytloun Yes, I have some problem within the external auth and now it works fine :)
