### ISSUE TITLE
Ejabberd Django External Authentication Failed

### ISSUE THREAD

**Issue by yashwanthbabu** [fpytloun/django-xmpp#3]
Hey,

I have created the ejaberd_auth.sh file and my .sh files looks like

```
#!/bin/bash
source /Users/yashwanthbabu/Documents/virtual_env/ejabberd/bin/activate
cd /Users/yashwanthbabu/Documents/Ejabberd_Chat
python manage.py ejabberd_auth $@ 
```

In my ejabberd config file, i have given like this for external authentication

```
auth_method: external
extauth_program: "/Users/yashwanthbabu/Documents/Movies/EABChat/ejabberd_auth.sh"
```

This doesn't works and raises the error as: 

```
extauth script has exitted abruptly with reason 'normal'
```

and also sometimes raises the `extauth call didnt receive response` error.. Could you please help me with ths

**Comment by fpytloun** [comment]
What ejabberd version do you have?
I have found some similar issue in ejabberd: https://github.com/processone/ejabberd/issues/80
I am using latest stable ejabberd which works fine.

You can also check Django logs if it doesn't output any errors.

**Comment by yashwanthbabu** [comment]
@fpytloun 
Facing this error repeatedly.

```
2015-06-30 15:08:09.215 [error] <0.776.0>@extauth:loop:132 extauth call '[<<"auth">>,<<"yashwanth">>,<<"localhost">>,<<"yankring">>]' didn't receive response
2015-06-30 15:08:09.215 [error] <0.773.0>@ejabberd_auth:is_user_exists:315 The authentication module ejabberd_auth_external returned an error
when checking user <<"yashwanth">> in server <<"localhost">>
Error message: badarg
2015-06-30 15:08:09.215 [warning] <0.773.0>@ejabberd_web_admin:process:207 Access of <<"yashwanth@localhost">> from <<"127.0.0.1">> failed with error: <<"inexistent-account">>
2015-06-30 15:09:09.229 [error] <0.784.0>@extauth:loop:132 extauth call '[<<"auth">>,<<"yashwanth">>,<<"localhost">>,<<"yankring">>]' didn't receive response
```

Regarding what is this error been raising??

And also [this](https://github.com/processone/ejabberd/blob/master/test/ejabberd_SUITE_data/extauth.py) external authentication script works fine. Whats difference in both?

**Comment by fpytloun** [comment]
`ejabberd_auth.py` has some debug messages. Can you enable debug logging and paste output of it?

Something like this may work, depending on your app:

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,

    'formatters': {
        'default': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },

    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/log/django.log',
            'formatter': 'default',
        },
    },

    # Loggers
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}
```

**Comment by yashwanthbabu** [comment]
@fpytloun Same above errors facing in the ejabberd.log . It just stucked with this log 

```
2015-06-30 10:31:04,743 [DEBUG] xmpp.management.commands.ejabberd_auth: Starting serving authentication requests for Ejabberd
```

and I cant able to login into the Ejabberd (http://localhost:5280/admin) server

**Comment by fpytloun** [comment]
Hm, it is really strange. I would expect to see `Command is isuser` or `An error has occurred during..`
Anyway it means that the script is stucked in `data = self.from_ejabberd()` probably when trying to read from stdin.

Only difference between script that you have linked and ours is that our auth is encoding stdin data:

```
    def from_ejabberd(self, encoding="utf-8"):
        """
        Reads data from stdin as passed by eJabberd
        """
        input_length = sys.stdin.read(2).encode(encoding)
        (size,) = struct.unpack(">h", input_length)
        return sys.stdin.read(size).split(":")
```

vs

```
    (pkt_size,) = struct.unpack('>H', sys.stdin.read(2))
    pkt = sys.stdin.read(pkt_size).split(':')
```

You can put some debugging code into `from_ejabberd` method to see what's really on stdin (if anything).

BTW what ejabberd version do you have? Maybe it behaves somehow differently than latest version.

**Comment by yashwanthbabu** [comment]
@fpytloun I am using 15.06 version and I think this is the latest version.  I entirely removed that auth script and using yours. Even your auth script too fails for me

**Comment by fpytloun** [comment]
Ok, I have tried to make a clean installation in docker container to reproduce the issue.
(Un)fortunately I got ejabberd authentication working without any issues on the first try.

**Procedure for testing purposes:**

Run docker:

```
docker run -h django-xmpp --name django-xmpp -i -t debian /bin/bash
```

Install what's required:

```
apt-get install python-pip
pip install django-xmpp

wget -O ejabberd.deb "https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/15.06/ejabberd_15.06-0_amd64.deb"
dpkg -i ejabberd.deb
```

Prepare django project:

```
django-admin startproject django_project
# Add xmpp into installed apps, eventually setup logging
cd django_project; python manage.py syncdb

cat << 'EOF' > ~/ejabberd_auth.sh
#!/bin/bash
cd ~/django_project
python manage.py ejabberd_auth $@
EOF
```

Setup ejabberd:

```
# edit /opt/ejabberd-15.06/conf/ejabberd.yml

host_config:
  django-xmpp:
    auth_method: external
    extauth_program: "/root/ejabberd_auth.sh"
```

Generate cert, put django-xmpp as common name:

```
cd /opt/ejabberd-15.06/conf
openssl req -new -x509 -newkey rsa:1024 -days 3650 -keyout privkey.pem -out server.pem
openssl rsa -in privkey.pem -out privkey.pem
cat privkey.pem >> server.pem
rm privkey.pem
```

Start ejabberd

```
/opt/ejabberd-15.06/bin/ejabberdctl start
```

Log in as django user on domain `django-xmpp`, set server manually to ip address of your container (run `ip a` in it)

**Comment by yashwanthbabu** [comment]
@fpytloun Thanks a lot. I will try this. And also I am trying the external authentication out of the django-xmpp. All my code is same as yours and trying it as separate app in my django project. Is this creating me the issue?? And also if possible please provide the above instructions which is related to Mac OSX

**Comment by fpytloun** [comment]
Unfortunately setup on OS X would be completely different. But you can run Linux VM in Virtualbox to test it.

**Comment by yashwanthbabu** [comment]
@fpytloun 

```
import sys
import logging
from struct import *

sys.stderr = open('/Users/yashwanthbabu/my-ejabberd/var/log/ejabberd/extauth_err4.log', 'w')
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s %(levelname)s %(message)s',
                    filename='/Users/yashwanthbabu/my-ejabberd/var/log/ejabberd/extauth_err4.log',
                    filemode='a')

logging.info('extauth script started, waiting for ejabberd requests')

def from_ejabberd():
    input_length = sys.stdin.read(2)
    logging.info("Bytes read: " + str(len(input_length)))
    logging.info("Input Length: " + str(input_length))
    (size,) = unpack('>h', input_length)
    return sys.stdin.read(size).split(':')

def to_ejabberd(bool):
    answer = 0
    if bool:
        answer = 1
    token = pack('>hh', 2, answer)
    sys.stdout.write(token)
    sys.stdout.flush()

def auth(username, server, password):
    return True

def isuser(username, server):
    return True

def setpass(username, server, password):
    return True

while True:
    data = from_ejabberd()
    success = False
    if data[0] == "auth":
        success = auth(data[1], data[2], data[3])
    elif data[0] == "isuser":
        success = isuser(data[1], data[2])
    elif data[0] == "setpass":
        success = setpass(data[1], data[2], data[3])
    to_ejabberd(success)
```

I am using this script which is entirely in python and doesn't includes any django part. With this script it works and in my ejabberd.yml i setted up with this line

```
auth_method: external
extauth_program: "python /Users/yashwanthbabu/Documents/ejabberd_auth.py"
```

Later on I tried to import the django related things then I am not able to work on
Whats the problem with this?? I would like to know what happens, why the django just can't run and can't log anything.

**Comment by yashwanthbabu** [comment]
@fpytloun Hey filip, Now its working. I have some issues related to my code and fixed now. Thanks for your support at all the time :+1: :)

**Comment by fpytloun** [comment]
Great, good to hear that! :-)
