### ISSUE TITLE
Uncaught Error in initConnection

### ISSUE THREAD

**Issue by alexandervlpl** [fpytloun/django-xmpp#8]
I added `django-xmpp` to my project (via `pip`) and configured external authentication exactly as described in the README. Authentication works perfectly in the front end, and using the demo client on conversejs.org I can log in and chat as a user of my site.

Unfortunately, on the page where I included `{% conversejs_initialize %}` I get the following error:

**converse.min.js:236 Uncaught Error: initConnection: If you use auto_login, you also need to provide a jid value**

Somehow, the authentication doesn't happen in the front end (converse doesn't know what credentials to use). Should they be passed in somehow? How can I debug this?

Thanks for this great project!

**Comment by alexandervlpl** [comment]
FYI: this happens when a user is logged in.

**Comment by fpytloun** [comment]
Hello,

checked the code (`xmpp/utils.py`) and I guess your problem is here:

```
    auth_type = getattr(settings, 'XMPP_CONVERSEJS_AUTH', None)

    if auth_type in ['login', 'prebind']:
        # We need to ensure XMPPAccount for both login and prebind auth
        xmpp_account = XMPPAccount.get_or_create(request.user)
        settings_auth['jid'] = xmpp_account.jid
```

You need to set `XMPP_CONVERSEJS_AUTH = "login"` in settings.
I can't remember why I didn't specify default value.. :-/

**Comment by alexandervlpl** [comment]
Thanks, that was the issue! I think I'll submit a PR for this once I'm done integrating.
