### ISSUE TITLE
Authentication problems with usernames containing uppercase letters

### ISSUE THREAD

**Issue by alexandervlpl** [fpytloun/django-xmpp#9]
Authentication fails with usernames that contain uppercase letters. I tried adding (or removing) `lower()` calls in various places (`models.py`, `templatetags/xmpp_tags.py`, `views.py`), but I still can't get this to work. Could this be a limitation of `ejabberd`, or is it possible to fix this on the Django side?

**Comment by fpytloun** [comment]
In my opinion JID should have the same rules as email address. And email addresses are usually case-insensitive. That's the reason why code is forcing lower-case and I think it should be left as is.

http://archive.jabber.org/userguide/#register

> Usernames are case-insensitive, so "StPeter" is the same as "stpeter". Also, Jabber usernames are limited to 1023 characters (not that you'll ever need a username that long, but just in case...). In addition, certain characters are not allowed in your username:

**Comment by alexandervlpl** [comment]
Agreed. The problem is that I'm adding chat to a system where many usernames already contain uppercase letters. Is changing them and notifying the users by email my only option :fearful: , or can you suggest a better solution?

**Comment by fpytloun** [comment]
I don't think it's necessary. Just use lower-case for jabber auth (which should be enforced by using `lower()` in code already, if not please make pull request) and keep mixed cases for regular user login.

**Comment by alexandervlpl** [comment]
Mixed case usernames are handled correctly now.
